basePath: /
definitions:
  http.credentials:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  http.orderDTO:
    properties:
      accrual:
        type: number
      number:
        type: string
      status:
        type: string
      uploaded_at:
        type: string
    type: object
  http.reqDTO:
    properties:
      order:
        type: string
      sum:
        type: number
    type: object
  http.respDTO:
    properties:
      current:
        type: number
      withdrawn:
        type: number
    type: object
  http.respItem:
    properties:
      order:
        type: string
      processed_at:
        type: string
      sum:
        type: number
    type: object
info:
  contact: {}
  title: Gophermart API
  version: "1.0"
paths:
  /api/user/balance:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.respDTO'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get user balance
  /api/user/balance/withdraw:
    post:
      parameters:
      - description: Withdraw info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.reqDTO'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "402":
          description: Payment Required
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Withdraw user balance
  /api/user/login:
    post:
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/http.credentials'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Login user
  /api/user/orders:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/http.orderDTO'
            type: array
        "204":
          description: No Content
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List user orders
    post:
      parameters:
      - description: Order number
        in: body
        name: number
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Already uploaded
          schema:
            type: string
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload order number
  /api/user/register:
    post:
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/http.credentials'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Register new user
  /api/user/withdrawals:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/http.respItem'
            type: array
        "204":
          description: No Content
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List user withdrawals
swagger: "2.0"
